# Adapted from https://github.com/numba/numba/blob/master/azure-pipelines.yml
jobs:
# # Mac and Linux use the same template
# - template: ci/azure/posix.yml
#   parameters:
#     name: macOS
#     vmImage: xcode9-macos10.13
# - template: .ci/azure/posix.yml
#   parameters:
#     name: Linux
#     vmImage: ubuntu-16.04

# Windows Python 2.7 needs VC 9.0 installed, handled in the template
- template: .ci/azure/windows.yml
  parameters:
    name: Windows
    vmImage: vs2017-win2016
